version: "3.9"

services:

  db:
    image: postgres:14.1
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "5432:5432"

  metabasedb:
    image: postgres:14.1
    volumes:
      - metabase_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${MB_DB_USER}
      POSTGRES_PASSWORD: ${MB_DB_PASSWORD}
      POSTGRES_DB: ${MB_DB_DBNAME}
    ports:
      - "5433:5432"

  migration:
    image: bazel/cmd/dbmigration:image
    environment:
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      DB_HOST: db
      DB_PORT: 5432

  jiracollector:
    image: bazel/cmd/jiracollector:image
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; run --logtostderr'
    environment:
      - JIRA_HOST
      - JIRA_USER
      - JIRA_AUTH_TOKEN
      - JIRA_QUERY
      - JIRA_EPIC_FIELD
      - JIRA_PROJECT
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
      - DB_HOST=db
      - DB_PORT=5432

  jiraissuecalculator:
    image: bazel/cmd/jiraissuecalculator:image
    environment:
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
      - DB_HOST=db
      - DB_PORT=5432
      - JIRA_PROJECT
      - WORK_START_STATES
      - WORK_TODO_STATES
      - WORK_COMPLETE_STATES

  metabase:
    image: metabase/metabase
    volumes:
      - metabase_data:/metabase-data
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_USER: ${MB_DB_USER}
      MB_DB_PASS: ${MB_DB_PASSWORD} 
      MB_DB_HOST: metabasedb

volumes:
  db_data:
  metabase_db_data:
  metabase_data:
