version: "3.9"

services:

  db:
    image: postgres:14.1
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "5432:5432"

  migration:
    image: bazel/cmd/dbmigration:image
    environment:
      - DB_USERNAME
      - DB_PASSWORD
      - DB_NAME
      - DB_HOST
      - DB_PORT

  jiracollector:
    image: bazel/cmd/jiracollector:image
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; run --logtostderr'
    environment:
      - JIRA_HOST
      - JIRA_USER
      - JIRA_AUTH_TOKEN
      - JIRA_QUERY
      - JIRA_EPIC_FIELD
      - JIRA_PROJECT
      - DB_USERNAME
      - DB_PASSWORD
      - DB_NAME
      - DB_HOST
      - DB_PORT

  jiraissuecalculator:
    image: bazel/cmd/jiraissuecalculator:image
    environment:
      - DB_USERNAME
      - DB_PASSWORD
      - DB_NAME
      - DB_HOST
      - DB_PORT
      - JIRA_PROJECT

volumes:
  db_data:
